
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Harshal
 */
public class Reservation extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    
   
    public Reservation() {
        initComponents();
         Connect();
         Loadstartplace();
         Loadendplace();
         
    }
    
    
    
     Connection con;
    preparedStatement pst ;
    ResultSet rs;
    
   
    
    
  
    
    public void Connect(){
    
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            con =  java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/railway?zeroDateTimeBehavior=CONVERT_TO_NULL","harshal", "harshal");
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(addtrain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(addtrain.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    
    }
    
    
    public void Loadstartplace()
    {
    
        try {
            PreparedStatement  pst =  con.prepareStatement("select splace from  traindetails ");
            
            rs = pst.executeQuery();
            txtsplace.removeAllItems();
            while(rs.next())
            {
            txtsplace.addItem(rs.getString(1) );
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Reservation.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }
    
    
    
    
    
     
    public void Loadendplace()
    {
    
        try {
            PreparedStatement  pst =  con.prepareStatement("select dplace from  traindetails ");
            
            rs = pst.executeQuery();
            txteplace.removeAllItems();
            while(rs.next())
            {
            txteplace.addItem(rs.getString(1) );
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Reservation.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }
    
    public void load()
    {
        try {
            String splace = txtsplace.getSelectedItem().toString();
            String eplace = txteplace.getSelectedItem().toString();
            
            PreparedStatement   pst =  con.prepareStatement("select * from traindetails where splace = ? and dplace = ? ");
            
            pst.setString(1, splace);
            pst.setString(2, eplace);
            rs = pst.executeQuery();
            
            if ( rs.next()== true)
            {
            
                txttno.setText(rs.getString(1));
                txttname.setText(rs.getString(2));
                 txtprice.setText(rs.getString(5));
                 txttime.setText(rs.getString(6));
            }
            else
            {
            JOptionPane.showMessageDialog(this, "Record Not Found");
            
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Reservation.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    
    
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtpassenger = new javax.swing.JTextField();
        txtsplace = new javax.swing.JComboBox<>();
        txteplace = new javax.swing.JComboBox<>();
        txttno = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        txttname = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        txttime = new javax.swing.JTextField();
        txtdate = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtticket1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(235, 199, 199));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Start place");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("End place");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 80, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Train no");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 80, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Train name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 100, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Time");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 57, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Date");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 80, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("No of tickets");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 100, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Total");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 90, -1));

        txtpassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassengerActionPerformed(evt);
            }
        });
        jPanel1.add(txtpassenger, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 190, 29));

        txtsplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsplaceActionPerformed(evt);
            }
        });
        jPanel1.add(txtsplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 186, 20));

        jPanel1.add(txteplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 186, 20));
        jPanel1.add(txttno, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 190, 29));

        txttotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txttotalMouseClicked(evt);
            }
        });
        txttotal.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txttotalInputMethodTextChanged(evt);
            }
        });
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });
        txttotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttotalKeyPressed(evt);
            }
        });
        jPanel1.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, 190, 30));
        jPanel1.add(txttname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 190, 30));

        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });
        jPanel1.add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 190, 30));

        txttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimeActionPerformed(evt);
            }
        });
        txttime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttimeKeyPressed(evt);
            }
        });
        jPanel1.add(txttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 190, 30));
        jPanel1.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 230, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Reserve");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 140, 60));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Reset");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 110, 50));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 110, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Reservation");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        txtticket1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtticket1ActionPerformed(evt);
            }
        });
        txtticket1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtticket1KeyPressed(evt);
            }
        });
        jPanel1.add(txtticket1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 190, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Price");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 57, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void txttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       load();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txttimeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimeKeyPressed
      
       
    }//GEN-LAST:event_txttimeKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        
            String username = txtpassenger.getText();
            String splace = txtsplace.getSelectedItem().toString();
            String eplace = txteplace.getSelectedItem().toString();
            String tno = txttno.getText();
            String tname = txttname.getText();
            String price = txtprice.getText();
            
            SimpleDateFormat date_form = new SimpleDateFormat("yyyy-MM-dd");
            String date = date_form.format(txtdate.getDate());
            String ticket = txtticket1.getText();
            String total = txttotal.getText();
             String time = txttime.getText();
             
            
            try{
            PreparedStatement pst = con.prepareStatement("insert into reservation (username,splace,eplace,tno,tname,price,time,date,ticket,total) values (?,?,?,?,?,?,?,?,?,?)");
                   pst.setString (1,username);
pst.setString (2, splace);
pst.setString (3, eplace);
pst.setString (4, tno);
pst.setString (5, tname);
pst.setString (6, price);
pst.setString (7, time);
pst.setString (8, date);
pst.setString (9, ticket);
pst.setString (10, total);
int k = pst.executeUpdate();
if (k==1)
{
    JOptionPane.showMessageDialog(this, "Record Added");
}
else
{
    JOptionPane.showMessageDialog(this, "Record Failed");
}

        } catch (SQLException ex) {
            Logger.getLogger(addtrain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
              
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtsplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsplaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsplaceActionPerformed

    private void txtpassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassengerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassengerActionPerformed

    private void txttotalInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txttotalInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalInputMethodTextChanged

    private void txttotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttotalMouseClicked
      
      
         
    }//GEN-LAST:event_txttotalMouseClicked

    private void txtticket1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtticket1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtticket1ActionPerformed

    private void txtticket1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtticket1KeyPressed
  int price,ticket,tot;
        
       if(evt.getKeyCode() == KeyEvent.VK_ENTER)
       {
       
           price = Integer.parseInt(txtprice.getText());
           ticket = Integer.parseInt(txtticket1.getText());
           
           tot = price * ticket;
           txttotal.setText(String.valueOf(tot));
       
       }     }//GEN-LAST:event_txtticket1KeyPressed

    private void txttotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttotalKeyPressed
        int price,ticket,tot;
        
       if(evt.getKeyCode() == KeyEvent.VK_ENTER)
       {
       
           price = Integer.parseInt(txtprice.getText());
           ticket = Integer.parseInt(txttime.getText());
           
           tot = price * ticket;
           txttotal.setText(String.valueOf(tot));
       
       }        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JComboBox<String> txteplace;
    private javax.swing.JTextField txtpassenger;
    private javax.swing.JTextField txtprice;
    private javax.swing.JComboBox<String> txtsplace;
    private javax.swing.JTextField txtticket1;
    private javax.swing.JTextField txttime;
    private javax.swing.JTextField txttname;
    private javax.swing.JTextField txttno;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables

    private static class preparedStatement {

        public preparedStatement() {
        }

        private ResultSet executeQuery() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
